# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8530463d0b0487232be80122699e86b7077534ca416a0458880b18618715ff84de41c4bd0e42ae087194a477ef5a0afb52379acdecab72f1dd300cfd42574bc6

test:
  secret_key_base: 13a80225416640ef52845d8e91ce41ce8598804f6b556cdfb906ae2d6300f342d1c9f87bb2cb0ed9e4223416aeb583570f7905423d060075b7a241192a0023c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
